# Generated by Django 4.0.6 on 2022-08-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_rename_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='region',
            field=models.CharField(choices=[('Toshkent', 'Toshkent'), ("Farg'ona", "Farg'ona"), ('Andijon', 'Andijon'), ('Samarqand', 'Samarqand'), ('Buxoro', 'Buxoro'), ('Navoiy', 'Navoiy'), ('Qarshi', 'Qarshi'), ('Nukus', 'Nukus'), ('Xorazm', 'Xorazm')], default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='applied_jobs',
            field=models.ManyToManyField(blank=True, related_name='applied_users', to='vacancy.vacancy'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='saved_jobs',
            field=models.ManyToManyField(blank=True, to='vacancy.vacancy'),
        ),
    ]
