# Generated by Django 4.0.6 on 2022-08-02 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_worker_region_alter_worker_applied_jobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='min_salary',
            field=models.IntegerField(default=9999999999),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_category', to='vacancy.category'),
        ),
    ]
