# Generated by Django 4.0.6 on 2022-08-07 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancy', '0004_category_max_salary_category_min_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='desired_job_title',
        ),
        migrations.AddField(
            model_name='worker',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='has_experience',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='has_portfoilo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='native_language',
            field=models.CharField(choices=[('Uzbek', 'Uzbek'), ('Russian', 'Russian'), ('English', 'English')], default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='telegram',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='WorkerPortfoilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfoilo', to='vacancy.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('language', models.CharField(choices=[('Uzbek', 'Uzbek'), ('Russian', 'Russian'), ('English', 'English')], max_length=56)),
                ('level', models.CharField(choices=[('A1 (Beginner)', 'A1 (Beginner)'), ('A2 (Elementary)', 'A2 (Elementary)'), ('B1 (Intermediate)', 'B1 (Intermediate)'), ('B2 (Upper-Intermediate)', 'B2 (Upper-Intermediate)'), ('C1 (Advanced)', 'C1 (Advanced)'), ('C2 (Proficiency)', 'C2 (Proficiency)')], max_length=128)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='vacancy.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('position', models.CharField(max_length=128)),
                ('organization', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('organization_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.category')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='vacancy.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerDesiredJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=128)),
                ('salary', models.IntegerField()),
                ('employment_type', models.CharField(choices=[('full work day', 'full work day'), ('partly work', 'partly work'), ('project work', 'project work'), ('voluntary work', 'voluntary work'), ('internship', 'internship')], max_length=28)),
                ('schedule', models.CharField(choices=[('full-time', 'full-time'), ('part-time', 'part-time'), ('flexible', 'flexible'), ('remote', 'remote'), ('shift method', 'shift method')], max_length=28)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.category')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desired_job', to='vacancy.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
