# Generated by Django 4.0.6 on 2023-11-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_remove_worker_desired_job_title_worker_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='min_salary',
            field=models.IntegerField(default=0),
        ),
    ]
