# Generated by Django 4.0.6 on 2023-12-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_alter_category_min_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='applied_jobs',
        ),
    ]
