# Generated by Django 4.0.6 on 2023-12-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0010_applicationfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerlanguages',
            name='level',
            field=models.CharField(choices=[('A1', 'A1 (Beginner)'), ('A2', 'A2 (Elementary)'), ('B1', 'B1 (Intermediate)'), ('B2', 'B2 (Upper-Intermediate)'), ('C1', 'C1 (Advanced)'), ('C2', 'C2 (Proficiency)')], max_length=128),
        ),
    ]
